#!/bin/bash
terraform_zip="terraform_0.11.7_linux_amd64.zip"
wget https://releases.hashicorp.com/terraform/0.11.7/$terraform_zip
unzip $terraform_zip
sudo cp terraform /usr/local/bin
rm -rf terraform*
exit 0
